### ISSUE TITLE
Unsupperted 16-bit application error

### ISSUE THREAD

**Issue by tbleken** [RickStrahl/SetResolution#2]
Hi Rick, 
on my machine, Win 11 Pro 64-bit, I get this error when I issue `sr /?` in a DOS command window: 
The program or feature "\??\c\bat\sr.exe" cannot start or run due to incompatibility with 64-bit versions of Windows...

**Comment by RickStrahl** [comment]
Hmmm... works for me.

![image](https://user-images.githubusercontent.com/1374013/208037905-0dc517ed-46c0-4fa6-a281-7b6cb7624968.png)

I wonder if you have maybe some other program call `sr` in your path? What happens if you rename or launch directly out of the install folder.

App is a .NET console app and it should work either on 32 bit or 64 bit versions of Windows. I'm running Windows 11.

+++ Rick ---

**Comment by tbleken** [comment]
I confess that I only downloaded two files, sr.exe (139 378 bytes) and setresolution.exe (140 028 bytes) and saved them in my Bat folder. I use this folder for several simple utilities, and it's in my path. 
I just downloaded the newer files, and got the same error. You mention Installation folder, do I need to install this program by using some kind of routine?
I do have another program called sr.exe, SlickRun (yes I know, old habits die hard), but renaming it didn't help.

Update: I clearly downloaded the wrong files. Works fine now.

**Comment by RickStrahl** [comment]
No there's no installation, you just copy the file(s) and run it. On Windows 10/11 this should just work since .NET is available and the console app should just run. 

I do wonder if perhaps the file is blocked because it's directly downloaded? Maybe you need to unblock? But I think you'd see a different error in that case.

I'm not sure why it wouldn't work that's why I say copy them to a different folder then run them out of that folder with with `.\sr.exe` (no parameters should also give you the command display page).

**Comment by tbleken** [comment]
Problem solved, as noted in my update message.
