### ISSUE TITLE
Is there a way to list the resolutions/refresh rates and the number of their combinations the same as the Windows 11 listing?

### ISSUE THREAD

**Issue by BeeDance** [RickStrahl/SetResolution#7]
![1](https://github.com/RickStrahl/SetResolution/assets/6102853/623e44f3-58ce-487b-b80d-90b80efd21a9)
![2](https://github.com/RickStrahl/SetResolution/assets/6102853/cb648d69-e93d-4380-809f-c74d65b788cc)
As shown in the picture, windows lists a total of 16 resolutions and 8 refresh rates, their combination is 16x8=128.
and the Sr.exe list 445 items, as this picture.is there a way list the data like windows 11?
![3](https://github.com/RickStrahl/SetResolution/assets/6102853/98ff5a15-0cd9-4605-949d-4dd91bb7bcab)

**Comment by RickStrahl** [comment]
Not sure how that would work. It works like that in Windows because you can interactively match the refresh rates and resolutions to each other - you can't really do that in a console app as the display is static. The idea is that you can pick a specific mode and create a pre-set so it's not like you'll be looking at the list very often.
